Repository Anudeep-313/mini-project, pull requests merged in 2022-10, with the labels that each got.

#4 Spelling Corrections
  index.html
Labels: invalid

#10 Changes in Readme
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#12 added some effects on footer
  index.html
  src/styles/index.css
Labels: hacktoberfest, hacktoberfest-accepted

#21 Added CSS to Footer
  .vscode/settings.json
  src/styles/index.css
Labels: hacktoberfest, hacktoberfest-accepted

#26 LoginModule
  signup.html
  src/assets/img1.jpg
  src/styles/signup.css
Labels: hacktoberfest, hacktoberfest-accepted

#15 new contributing rules added
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest-accepted

#23 UI Design Changes
  index.html
  src/index.js
  src/styles/index.css
Labels: hacktoberfest, hacktoberfest-accepted

#36 Updated UI
  index.html
  src/styles/index.css
Labels: hacktoberfest, hacktoberfest-accepted

#47 Update readme file
  .vscode/settings.json
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#52 add tech stack in readme.md
  README.md
Labels: hacktoberfest-accepted

#55 Added Github and Linkedin Buttons
  about.html
  index.html
  src/assets/github.svg
  src/assets/linkedin.svg
  src/styles/index.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#58 I have designed the logos
  README.md
  index.html
  src/assets/logo-1.png
  src/assets/logo-2.png
  src/assets/logo-icon.png
Labels: hacktoberfest, hacktoberfest-accepted

#63 Added backend using php
  backend/db_conn.php
  backend/login.php
  backend/logout.php
  backend/profile.php
Labels: hacktoberfest, hacktoberfest-accepted

#59 Added header and typewriter effect
  about.html
  src/styles/about.css
Labels: hacktoberfest-accepted

#60 beautified the contributing.md file
  CONTRIBUTING.md
Labels: hacktoberfest-accepted
